flask:
    DEBUG: True
    SECRET_KEY: 'put-your-secret-key-here'
    DEFAULT_ALLOW_ORIGINS:
        - 'http://localhost'
    # Places
    DEFAULT_LOCATION: [51.7531, -1.2584]
    OSM_IMPORT_URL: 'http://download.geofabrik.de/openstreetmap/europe/great_britain/england/oxfordshire.osm.bz2'
    OXPOINTS_IMPORT_URL: 'http://oxpoints.oucs.ox.ac.uk/all.json'
    NAPTAN_IMPORT_URL: 'http://www.dft.gov.uk/NaPTAN/snapshot/NaPTANxml.zip'

blueprints:
    places:
        url_prefix: /places
        factory: moxie.places.create_blueprint

services:
    places:
        POIService:
            nearby_excludes: ['/university/library/sub-library', '/university/room']
        TransportService:
            providers:
                moxie.transport.providers.cloudamber.CloudAmberBusRtiProvider:
                    url: 'http://www.oxontime.com'
        SearchService:
            backend_uri: 'solr+http://localhost:8080/solr/places'
        KVService:
            backend_uri: 'redis://localhost:6379/0'

healthchecks:
    moxie.core.search.SearchService:
            backend_uri: 'solr+http://localhost:8080/solr/places'
    moxie.core.kv.KVService:
            backend_uri: 'redis://localhost:6379/0'
